### ISSUE TITLE
SEA not working on iOS/Android

### ISSUE THREAD

**Issue by adamblvck** [alterx/gundb-expo-sqlite-adapter#1]
Hi there!
Thank you for this wonderful code and repo. The SQLite adaptor seems to be working well: gun data is nicely persisted over time.

In this issue, however, I'd like to bring attention to SEA encryption/decryption aspects not working when trying to run on iOS/Android. In particular, the error seems to come through when importing SEA.

```
import SEA from 'gun/sea';
```

This causes METRO to tap out by stating "dynamic imports are not supported".
Does anyone else experience similar behaviour?

For context; gun installed through with the latest version in mind.

```
expo install gun
```

Have a wonderful day!

**Comment by TerranFenrir** [comment]
> Hi there! Thank you for this wonderful code and repo. The SQLite adaptor seems to be working well: gun data is nicely persisted over time.
> 
> In this issue, however, I'd like to bring attention to SEA encryption/decryption aspects not working when trying to run on iOS/Android. In particular, the error seems to come through when importing SEA.
> 
> ```
> import SEA from 'gun/sea';
> ```
> 
> This causes METRO to tap out by stating "dynamic imports are not supported". Does anyone else experience similar behaviour?
> 
> For context; gun installed through with the latest version in mind.
> 
> ```
> expo install gun
> ```
> 
> Have a wonderful day!

Hey there! Sorry if this reply would be useful or not now, but here is the solution to the problem faced while importing SEA in ReactNative:

1) Open ./node_modules/webview-crypto/src/MainWorker.ts then replace `import serializeError = require("serialize-error");` with
```
import serializeError from "serialize-error";
```

2) After that ./node_modules/webview-crypto/src/asyncSerialize.ts to replace `import find = require("lodash/find");` with 
```
import find from "lodash/find";
```

I myself got this solution from this [project](https://github.com/aethiop/jot)

**Comment by adamblvck** [comment]
@Zevenstreity thank you for this information. I've created a [bash script](https://gist.github.com/adamblvck/4a06ee4bd04d9c00c53ab17bc500d088) to quickly apply these changes to a local node_modules folder, after  a `npm install` or `expo install`.
